apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 942304845351.dkr.ecr.eu-west-3.amazonaws.com/user-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-user:5432/user_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: SERVICES_AUTHENTICATION_SERVICE_URL
              value: http://authentication-service:8082
              # Cette fois, authentication-service existe DÉJÀ (déployé à
              # l'étape 3) — la communication va réellement fonctionner,
              # contrairement à la référence "dans le vide" qu'on avait
              # dans l'autre sens tout à l'heure.

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8083
      targetPort: 8083